$ErrorActionPreference='Stop'
$officeRoot=Split-Path $PSScriptRoot -Parent
$officeOutput=Join-Path $officeRoot 'runtime/action-training-phase/office/evaluation-smol-union18-trainscene-chunk32'
$officeMonitor=Join-Path $officeRoot 'runtime/action-training-phase/office/evaluation-smol-union18-trainscene-chunk32-host-memory.json'
if(Test-Path -LiteralPath $officeOutput){throw 'Refuse to overwrite prior familiar-scene diagnostic'}
$officeContract=Join-Path $officeRoot 'runtime/action-training-phase/office/comparison-v6/frozen-contract.json'
$officeControl=[ordered]@{scope='Prospective chunk32 training-scene temporal diagnostic; never held-out success or sealed selection';checkpoint_contract_sha256=(Get-FileHash -LiteralPath $officeContract -Algorithm SHA256).Hash.ToLower();seed=1000;task='red-left';wording='train';policy_rng_seed=510000;chunk_execution=32;max_steps=585;physics_and_grader='unchanged office simulation and independent physical/strict grader';prediction_trace='retain full chunks, first three actual RGB/state inputs and hashes'}
$officeControl|ConvertTo-Json -Depth 4|Set-Content -LiteralPath (Join-Path $officeRoot 'runtime/action-training-phase/office/control-smol18-trainscene-chunk32-prospective.json') -Encoding utf8
Start-Process pwsh -WindowStyle Hidden -ArgumentList @('-NoProfile','-File',"$PSScriptRoot/office_monitor_host.ps1",'-OutputPath',$officeMonitor,'-EvaluationPath',$officeOutput,'-Seconds','500')
& wsl -d Ubuntu-24.04 -- bash -lc "cd /mnt/d/git/qwen-image_benchmark && env CUDA_VISIBLE_DEVICES='' MUJOCO_GL=osmesa PYOPENGL_PLATFORM=osmesa LD_LIBRARY_PATH=/mnt/d/git/qwen-image_benchmark/runtime/action-training-phase/office/osmesa-libs/root/usr/lib/x86_64-linux-gnu OMP_NUM_THREADS=4 PYTHONPATH=/mnt/d/git/qwen-image_benchmark/scripts OFFICE_COMPARISON_MODEL=smolvla OFFICE_REMOTE_SESSION=union18-train1000-chunk32 runtime/lerobot-teaser-env/bin/python scripts/office_guarded_eval.py --host-monitor /mnt/d/git/qwen-image_benchmark/runtime/action-training-phase/office/evaluation-smol-union18-trainscene-chunk32-host-memory.json --output runtime/action-training-phase/office/evaluation-smol-union18-trainscene-chunk32 --max-seconds 500 -- runtime/lerobot-teaser-env/bin/python scripts/office_evaluate.py --checkpoint runtime/action-training-phase/office/comparison-v6/frozen-contract.json --policy-module office_comparison_adapter --device cpu --output runtime/action-training-phase/office/evaluation-smol-union18-trainscene-chunk32 --split validation --seeds 1000 --tasks red-left --wording train --development-training-scenes --image-size 256 --chunk-execution 32 --max-steps 585 --policy-rng-seed-fixed 510000 --retain-predictions --host-monitor /mnt/d/git/qwen-image_benchmark/runtime/action-training-phase/office/evaluation-smol-union18-trainscene-chunk32-host-memory.json --concurrency-note 'TRAINING-SCENE diagnostic; no held-out success claim'" *> (Join-Path $officeRoot 'runtime/action-training-phase/office/evaluation-smol-union18-trainscene-chunk32-stdout.log')
if($LASTEXITCODE -ne 0){throw 'Familiar-scene diagnostic failure retained'}
